[package]
name = "gxt-api-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "gxt_api_python"
crate-type = ["cdylib"]

[dependencies]
serde_json.workspace = true
pyo3 = "0.25.0"
gxt = { version = "0.13.0", path = "../gxt" }
