[package]
name = "gxt-cli"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "GXT command-line interface"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1"
serde_json = "1"
serde_cbor = "0.11"
ed25519-dalek = "2"
rand = "0.8"
hex = "0.4"
gxt = { path = "../gxt" }

[[bin]]
name = "gxt"
path = "src/main.rs"
