[package]
name = "gxt-cli"
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "GXT command-line interface"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1"
serde_json.workspace = true
gxt = { path = "../gxt" }

[[bin]]
name = "gxt"
path = "src/main.rs"
