[package]
name = "gxt-cli"
description = "GXT command-line interface"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1"
serde_json.workspace = true
gxt = { version = "0.5.0", path = "../gxt" }

[[bin]]
name = "gxt"
path = "src/main.rs"
