[package]
name = "gxt-cli"
version = "1.6.0"
description.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
readme = "../README.md"

[dependencies]
gxt.workspace = true
serde.workspace = true
serde_json.workspace = true
hex.workspace = true
clap = { version = "4.5", features = ["derive"] }
anyhow = "1"
hkdf = "0.12"
sha2 = "0.10"
x25519-dalek = { version = "2", features = ["static_secrets"] }
ed25519-dalek = "2"
rand_core = "0.6"

[[bin]]
name = "gxt"
path = "src/main.rs"
