[package]
name = "gxt-api-extism"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "gxt"
crate-type = ["cdylib"]

[dependencies]
serde_cbor.workspace = true
serde_json.workspace = true
extism-pdk = "1.3.0"
serde = { version = "1", features = ["derive"] }
gxt = { version = "0.14.0", path = "../gxt" }
