[profile.dev]
panic = "abort" # abort on panic!()

[profile.release]
panic = "abort"   # abort on panic!()
opt-level = "z"   # optimize for small code size
lto = true        # enable link time optimization
codegen-units = 1 # use a single codegen-unit for better optimizations
