[package]
name = "gxt"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "GXT: tiny signed game exchange tokens (library)"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_cbor = "0.11"
ed25519-dalek = "2"
blake3 = "1.5"
brotli = "3"
bs58 = "0.5"
thiserror = "1"
hex = "0.4"
x25519-dalek = "1"
chacha20poly1305 = "0.10"
rand = "0.8"
