[package]
name = "gxt"
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "GXT: tiny signed game exchange tokens (library)"

[dependencies]
serde_json.workspace = true
serde_cbor = "0.11"
ed25519-dalek = { version = "2", features = ["rand_core"] }
hex = "0.4"
serde = { version = "1", features = ["derive"] }
blake3 = "1.5"
brotli = "3"
bs58 = "0.5"
thiserror = "1"
x25519-dalek = "1"
chacha20poly1305 = "0.10"
rand = "0.8"
