name: Publish release

permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create release
        id: create_release
        uses: "softprops/action-gh-release@v2"
        with:
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: cargo test -p gxt --verbose

      - name: Run build
        run: |
          cargo build -p gxt-cli -p gxt-api-c --release
          strip --strip-all ./target/release/gxt

          mkdir -p assets/shared
          mv ./target/release/libgxt_c.so assets/shared/libgxt.so

          mkdir -p assets/static
          mv ./target/release/libgxt_c.a assets/static/libgxt.a

          mkdir -p assets/include
          mv ./target/release/gxt.h assets/include/

          mv ./target/release/gxt assets/
          tar czf gxt-linux.tar.gz assets/*

      - name: Upload release
        id: upload-release-linux
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: gxt-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    needs: release

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: cargo test -p gxt --verbose

      - name: Run build
        run: |
          cargo build -p gxt-cli -p gxt-api-c --release

          mkdir -p assets/shared
          mv ./target/release/libgxt_c.dylib assets/shared/libgxt.dylib

          mkdir -p assets/static
          mv ./target/release/libgxt_c.a assets/static/libgxt.a

          mkdir -p assets/include
          mv ./target/release/gxt.h assets/include/

          mv ./target/release/gxt assets/
          tar czf gxt-macos.tar.gz assets/*

      - name: Upload release
        id: upload-release-macos
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: gxt-macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-2025
    needs: release

    steps:
      - uses: actions/checkout@v2

      - name: Run build
        run: |
          cargo build -p gxt-cli -p gxt-api-c --release

          mkdir -p assets/shared
          mv ./target/release/gxt_c.dll assets/shared/gxt.dll

          mkdir -p assets/static
          mv ./target/release/gxt_c.lib assets/static/gxt.lib

          mkdir -p assets/include
          mv ./target/release/gxt.h assets/include/

          mv ./target/release/gxt.exe assets/

          Compress-Archive -Path assets\* -DestinationPath gxt-win.zip -Force

      - name: Upload release
        id: upload-release-windows
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: gxt-win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
