name: Publish release

permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create release
        id: create_release
        uses: "softprops/action-gh-release@v2"
        with:
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: cargo test -p gxc --verbose

      - name: Run build
        run: |
          cargo build -p gxt-cli --release
          strip --strip-all ./target/release/gxc
          mv ./target/release/gxc ./target/release/gxc-linux

      - name: Upload release
        id: upload-release-linux
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ./target/release/gxc-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    needs: release

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: cargo test -p gxc --verbose

      - name: Run build
        run: |
          cargo build -p gxt-cli --release
          mv ./target/release/gxc ./target/release/gxc-macos

      - name: Upload release
        id: upload-release-macos
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ./target/release/gxc-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-windows:
    runs-on: windows-2019
    needs: release

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: cargo test -p gxc --verbose

      - name: Run build
        run: cargo build -p gxt-cli --release

      - name: Upload release
        id: upload-release-windows
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ./target/release/gxc.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
